import { Artifact } from "./types";

export const COMPTON_CENTER: [number, number] = [-118.2201, 33.8958];

export const SAMPLE_ARTIFACTS: Artifact[] = [
  {
    id: "a1",
    type: "song_snippet",
    title: "Straight Outta Compton",
    creator: "N.W.A",
    year: 1988,
    location: { name: "Compton Civic Center", lat: 33.8958, lng: -118.2201 },
    resource: {
      provider: "youtube",
      url: "https://www.youtube.com/watch?v=TMZi25Pq3T8",
      startSec: 40,
      endSec: 58,
    },
    overlayText: "Straight outta Compton...",
    tags: ["N.W.A", "West Coast", "Compton"],
    weight: 1,
  },
  {
    id: "a2",
    type: "song_snippet",
    title: "Born and Raised in Compton",
    creator: "DJ Quik",
    year: 1991,
    location: { name: "Compton College area", lat: 33.904, lng: -118.229 },
    resource: {
      provider: "youtube",
      url: "https://www.youtube.com/watch?v=pQ_YA5wzA2Y",
      startSec: 18,
      endSec: 40,
    },
    overlayText: "Born and raised in Compton",
    tags: ["DJ Quik", "Compton"],
    weight: 0.9,
  },
  {
    id: "a3",
    type: "music_video",
    title: "Rosecrans",
    creator: "DJ Quik feat. Problem",
    year: 2016,
    location: { name: "Rosecrans Ave corridor", lat: 33.9038, lng: -118.2153 },
    resource: {
      provider: "youtube",
      url: "https://www.youtube.com/watch?v=iaL9zR2l8Vw",
      startSec: 25,
    },
    tags: ["Rosecrans", "Compton"],
    weight: 0.85,
  },
  {
    id: "a4",
    type: "music_video",
    title: "King Kunta",
    creator: "Kendrick Lamar",
    year: 2015,
    location: { name: "Compton city center", lat: 33.8962, lng: -118.2195 },
    resource: {
      provider: "youtube",
      url: "https://www.youtube.com/watch?v=hRK7PVJFbS8",
      startSec: 65,
    },
    tags: ["Kendrick Lamar", "Compton"],
    weight: 0.8,
  },
  {
    id: "a5",
    type: "film_snippet",
    title: "Straight Outta Compton (Trailer)",
    creator: "Universal Pictures",
    year: 2015,
    location: { name: "Compton Courthouse", lat: 33.8962, lng: -118.2195 },
    resource: {
      provider: "youtube",
      url: "https://www.youtube.com/watch?v=rsbWEF1Sju0",
      startSec: 48,
      endSec: 84,
    },
    overlayText: "Film scene reference near civic center.",
    tags: ["film", "N.W.A", "Compton"],
    weight: 0.75,
  },
  {
    id: "a6",
    type: "film_snippet",
    title: "The Defiant Ones (Dr. Dre segment)",
    creator: "HBO",
    year: 2017,
    location: { name: "Willowbrook Ave", lat: 33.9015, lng: -118.2195 },
    resource: {
      provider: "youtube",
      url: "https://www.youtube.com/watch?v=0M4B5M6D0ow",
      startSec: 30,
    },
    tags: ["documentary", "Dr. Dre"],
    weight: 0.7,
  },
  {
    id: "a7",
    type: "image",
    title: "Compton Courthouse district",
    creator: "Wikimedia Commons",
    location: { name: "Compton Courthouse", lat: 33.8962, lng: -118.2195 },
    resource: {
      provider: "image_url",
      url: "https://upload.wikimedia.org/wikipedia/commons/7/77/Compton%2C_California.jpg",
    },
    overlayText: "City imagery used in many cultural retrospectives.",
    tags: ["image", "cityscape"],
    weight: 0.6,
  },
  {
    id: "a8",
    type: "image",
    title: "Rosecrans and neighborhood streetscape",
    creator: "Public domain reference",
    location: { name: "Rosecrans Ave", lat: 33.906, lng: -118.215 },
    resource: {
      provider: "image_url",
      url: "https://upload.wikimedia.org/wikipedia/commons/5/5a/Rosecrans_Avenue.jpg",
    },
    tags: ["image", "streets"],
    weight: 0.55,
  },
];
