import { CulturalArtifact, LocationNode } from "./types";

export const COMPTON_CENTER: [number, number] = [-118.2201, 33.8958];

export const SAMPLE_LOCATIONS: LocationNode[] = [
  {
    id: "loc-city-hall",
    lat: 33.8958,
    lng: -118.2201,
    name: "Compton City Hall",
    neighborhood: "Civic Center",
  },
  {
    id: "loc-courthouse",
    lat: 33.8962,
    lng: -118.2195,
    name: "Compton Courthouse",
    neighborhood: "Downtown",
  },
  {
    id: "loc-centennial",
    lat: 33.898,
    lng: -118.219,
    name: "Centennial High School",
    neighborhood: "Central Compton",
  },
  {
    id: "loc-rosecrans",
    lat: 33.906,
    lng: -118.215,
    name: "Rosecrans Ave",
    neighborhood: "North Compton",
  },
  {
    id: "loc-downtown",
    lat: 33.8955,
    lng: -118.2215,
    name: "Downtown Compton",
    neighborhood: "Downtown",
  },
];

export const SAMPLE_ARTIFACTS: CulturalArtifact[] = [
  {
    id: "art-rosecrans-compton",
    type: "lyric-snippet",
    locationId: "loc-rosecrans",
    title: "Weekend on Rosecrans",
    creator: "Kendrick Lamar",
    sourceTitle: "Compton (feat. Dr. Dre)",
    year: 2012,
    caption: "Won't you spend a weekend on Rosecrans...",
    description:
      "A direct Rosecrans reference that makes the street itself part of the song's Compton geography.",
    tags: ["lyric", "rosecrans", "good kid m.A.A.d city"],
    heatWeight: 1,
    resource: {
      kind: "spotify",
      url: "https://open.spotify.com/track/1wf4LnpdAhLaoI2WwYDKAE",
    },
  },
  {
    id: "art-centennial-state-of-mind",
    type: "lyric-snippet",
    locationId: "loc-centennial",
    title: "Centennial High reference",
    creator: "Kendrick Lamar",
    sourceTitle: "Compton State of Mind",
    year: 2009,
    caption: "Centennial High, had me swimming with a pool of sharks.",
    tags: ["lyric", "centennial", "mixtape"],
    heatWeight: 0.96,
    resource: {
      kind: "spotify",
      url: "https://open.spotify.com/track/7Chwj6TpudcbeP50gk2jou",
    },
  },
  {
    id: "art-cityhall-not-like-us",
    type: "music-video",
    locationId: "loc-city-hall",
    title: "Not Like Us crowd sequence",
    creator: "Kendrick Lamar",
    sourceTitle: "Not Like Us",
    year: 2024,
    caption: "Victory-lap visuals filmed around Compton civic landmarks.",
    tags: ["video", "city hall", "mustard"],
    heatWeight: 1,
    resource: {
      kind: "youtube",
      url: "https://www.youtube.com/watch?v=H58vbez_m4E",
      startSeconds: 115,
    },
  },
  {
    id: "art-cityhall-key-photo",
    type: "image",
    locationId: "loc-city-hall",
    title: "Key to the City ceremony photos",
    creator: "Getty Images",
    sourceTitle: "Key to the City Ceremony with Kendrick Lamar",
    year: 2016,
    caption: "Photo archive from Kendrick Lamar receiving the key to Compton.",
    tags: ["photo", "city hall", "ceremony"],
    heatWeight: 0.72,
    resource: {
      kind: "image",
      sourceUrl:
        "https://www.gettyimages.co.uk/photos/key-to-the-city-ceremony-with-kendrick-lamar",
      credit: "Getty Images",
    },
  },
  {
    id: "art-courthouse-soc",
    type: "film-snippet",
    locationId: "loc-courthouse",
    title: "Straight Outta Compton courthouse reference",
    creator: "Universal Pictures",
    sourceTitle: "Straight Outta Compton",
    year: 2015,
    caption: "Film-related reference connected to the courthouse block during production in Compton.",
    tags: ["film", "nwa", "courthouse"],
    heatWeight: 0.9,
    resource: {
      kind: "youtube",
      url: "https://www.youtube.com/watch?v=RS1rYL19APQ",
      startSeconds: 44,
    },
  },
  {
    id: "art-centennial-bompton",
    type: "film-snippet",
    locationId: "loc-centennial",
    title: "NOISEY Bompton: Centennial segment",
    creator: "VICE / NOISEY",
    sourceTitle: "Bompton: Growing Up With Kendrick Lamar",
    year: 2016,
    caption: "Documentary footage revisiting Centennial High as part of Kendrick's story.",
    tags: ["documentary", "vice", "centennial"],
    heatWeight: 0.85,
    resource: {
      kind: "youtube",
      url: "https://www.youtube.com/watch?v=CA1EmLFi4OA",
      startSeconds: 170,
    },
  },
  {
    id: "art-downtown-king-kunta",
    type: "music-video",
    locationId: "loc-downtown",
    title: "King Kunta downtown visual",
    creator: "Kendrick Lamar",
    sourceTitle: "King Kunta",
    year: 2015,
    caption: "Compton street-level performance imagery that turned downtown into a stage.",
    tags: ["video", "downtown", "to pimp a butterfly"],
    heatWeight: 0.94,
    resource: {
      kind: "youtube",
      url: "https://www.youtube.com/watch?v=hRK7PVJFbS8",
      startSeconds: 24,
    },
  },
  {
    id: "art-downtown-soc-track",
    type: "lyric-snippet",
    locationId: "loc-downtown",
    title: "Straight Outta Compton anthem",
    creator: "N.W.A",
    sourceTitle: "Straight Outta Compton",
    year: 1988,
    caption: "Straight outta Compton, crazy motherf***** named Ice Cube.",
    tags: ["lyric", "nwa", "anthem"],
    heatWeight: 0.98,
    resource: {
      kind: "spotify",
      url: "https://open.spotify.com/track/1kGG0kfHYGrff4sWsXMdtE",
    },
  },
  {
    id: "art-rosecrans-tams",
    type: "image",
    locationId: "loc-rosecrans",
    title: "Tam's Burgers mural moment",
    creator: "NBC Los Angeles",
    sourceTitle: "Tam's Burgers honors Kendrick Lamar",
    year: 2024,
    caption: "\"They Not Like Us\" mural outside Tam's No. 21 after the video shoot.",
    tags: ["image", "tams", "rosecrans"],
    heatWeight: 0.78,
    resource: {
      kind: "external",
      url: "https://www.nbclosangeles.com/news/local/tams-burgers-honors-kendrick-lamar-with-mural-following-not-like-us-music-video/3457259/",
      label: "Article source",
    },
  },
  {
    id: "art-courthouse-not-like-us",
    type: "music-video",
    locationId: "loc-courthouse",
    title: "Not Like Us courthouse sequence",
    creator: "Kendrick Lamar",
    sourceTitle: "Not Like Us",
    year: 2024,
    caption: "\"They not like us\" echoed through multiple Compton civic landmarks, including the courthouse block.",
    tags: ["video", "courthouse", "victory-lap"],
    heatWeight: 0.88,
    resource: {
      kind: "youtube",
      url: "https://www.youtube.com/watch?v=H58vbez_m4E",
      startSeconds: 145,
    },
  },
];
